wamv: #namespace
    
    
    propeller_high_speed: 1 # High Propeller Speed             
    propeller_low_speed: -1 # Low Propeller Speed
    max_angular_speed: 1.0 # Maximum Base Turn Angular speed
   
    angular_high_speed: 0.785 # Maximum Base Turn Angular speed
    angular_low_speed: -0.785 # Maximum Base Turn Angular speed
    work_space: # 3D cube in which Drone is allowed to move
      x_max: 25.0
      x_min: -5.0
      y_max: -5.0
      y_min: -65.0
    # work_space: # 3D cube in which Drone is allowed to move
    #   x_max: 30.0
    #   x_min: -30.0
    #   y_max: -5.0
    #   y_min: -65.0

    # desired_point:
    #   x: 20.0
    #   y: -42.0
    #   z: 1.0

    desired_point:
      x: 4.0
      y: -58.0
      z: 0.0

    desired_point_epsilon: 3.0
    desired_collison_epsilon: 1.0
    max_distance_from_des_point: 68.0 # Maximum distance regitered in observations, has to be bigger than the largest distance of the workspace.
    
    number_decimals_precision_obs: 2

    # done_reward: 1000.0 # reward
    closer_to_point_reward: 100.0 # reward
    done_reward: 1000.0
    collision_reward: -2000.0
    closer_to_point_coeff: 500.0 